[package]
name = "rusty-notes-sqlite"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rusty-notes-domain = { workspace = true }
rusty-notes-application = { workspace = true }
rusqlite = { workspace = true }

[dev-dependencies]
rusty-notes-test-support = { workspace = true }
tempfile = { workspace = true }
